### ISSUE TITLE
Trouble running ray_integration/launch_simple.py

### ISSUE THREAD

**Issue by robertnishihara** [diux-dev/cluster#1]
A couple comments. I had to add

```
export AWS_DEFAULT_REGION=us-west-2
```

Then had to run `python launch_simple.py`. Running `./launch_simple.py` didn't quite work because `launch_simple.py` is not executable.

Then `launch_simple.py` seems to do an infinite loop for me.  Output so far is attached. The only error I see is 

```
mkdir: /temp/tasklogs/simple/0: Permission denied
```

[output.txt](https://github.com/diux-dev/cluster/files/1523093/output.txt)

**Comment by yaroslavvb** [comment]
Can you see if this commit works? It should now write to /tmp instead of /temp, I'm assuming /tmp is writeable which is true on my MacOS and Ubuntu 16.04

**Comment by yaroslavvb** [comment]
ps, the reason I chose /temp instead of /tmp is because system reboot wipes /tmp, but it turned out tasklogs are not that useful so it should be ok to lose them sometimes

**Comment by robertnishihara** [comment]
Yep, it works now. I was able to ssh just fine. Nothing much is supposed to be installed on the machine, right?

**Comment by yaroslavvb** [comment]
Nope, it installs everything from scratch, it's the "INSTALL_SCRIPT" parameter inside "launch_simple.py" and "launch_ray.py"
