### ISSUE TITLE
do logging onto EFS instead of EBS

### ISSUE THREAD

**Issue by yaroslavvb** [diux-dev/cluster#29]
EFS provides 50-100MB/second at lowest tier, so should be enough for most logging.

Step 1: duplicate recording all important stuff to both EBS/EFS. Make sure timing didn't change
Step 2: remove most EBS logging. This makes "snapshotting" a bit more useful since you are not carrying unneded logs around

cc @bearpelican

**Comment by bearpelican** [comment]
Fixed - https://github.com/diux-dev/cluster/pull/69
