### ISSUE TITLE
ImageNet: batch-size doesn't get logged after refactor

### ISSUE THREAD

**Issue by yaroslavvb** [diux-dev/cluster#51]
It's stuck on 128
cc @bearpelican 
<img width="399" alt="screenshot 2018-08-08 18 46 09" src="https://user-images.githubusercontent.com/23068/43873412-62ed1778-9b3b-11e8-80f3-0ddbfdec817e.png">

**Comment by yaroslavvb** [comment]
nvm, just tried with fresh run, and it seems to correctly reflect batch

**Comment by bearpelican** [comment]
This should fix the edge case where we change batch size without changing the dataloader
