### ISSUE TITLE
nexus -> ncluster rename

### ISSUE THREAD

**Issue by yaroslavvb** [diux-dev/cluster#65]

**Comment by yaroslavvb** [comment]
This part is done in https://github.com/diux-dev/ncluster

**Comment by bearpelican** [comment]
Woohoo! 
Is the plan to move cluster imagenet training over to ncluster?

**Comment by bearpelican** [comment]
Ahh got it. Ok see if I can get it working then

**Comment by yaroslavvb** [comment]
actually it's not yet read, it's *being* done, `make_task` works, but not make_job, I'll update this issue when it's fully done

**Comment by yaroslavvb** [comment]
How's the 4 machine run with refactored model?

**Comment by bearpelican** [comment]
Works like before as far as I can tell. I'll try to get a new baseline for it

**Comment by yaroslavvb** [comment]
Done
