### ISSUE TITLE
make imagenet18 snapshots available

### ISSUE THREAD

**Issue by yaroslavvb** [diux-dev/cluster#67]
Right now it's called
"imagenet_blank snapshot [Copied snap-0d37b903e01bb794a from us-east-1] "

need to rename/replicate this over regions

**Comment by bearpelican** [comment]
snapshot: snap-042f31eb766e01edb
region: us-west-2 

ami: pytorch.imagenet.source.v7
region: us-west-2, us-east-2, us-east-1

instance: i-0a1b9db0a6825d4f4, i-0e186a603f7035a5a, i-0db03b7b1262aee52, i-0db1b9e1e9bc76db0
region: us-east-1

**Comment by yaroslavvb** [comment]
PS, t3 instances were launched last week. They are faster and cheaper

**Comment by bearpelican** [comment]
ah nice. I'll use that!

Yup AMI has it. So you could just use those instances data without attaching a separate EBS volume.
Note: if you go that route, you must create the instance with `--attach-volume ''` so that the iops limit is higher

It use to be on EFS, but I forgot to upload to S3.

**Comment by yaroslavvb** [comment]
Oh nice, that simplifies things a bit, no need to have expensive EBS's
hanging around

**Comment by bearpelican** [comment]
This has all the imagenet resizes. Should be all that we need
https://s3.amazonaws.com/yaroslavvb/imagenet-sz-all.tar

**Comment by yaroslavvb** [comment]
this is no longer needed for release since AMI has the files needed
