### ISSUE TITLE
Dataset URL Access Denied

### ISSUE THREAD

**Issue by ymjiang** [diux-dev/cluster#73]
Hi. In README, there are two links for imagenet dataset. But I can't access them due to "AccessDenied".

Could anyone help me with this? Thanks in advance.

https://s3.amazonaws.com/yaroslavvb/imagenet-data-sorted.tar
https://s3.amazonaws.com/yaroslavvb/imagenet-sz.tar

Perhaps I should ping @yaroslavvb

**Comment by yaroslavvb** [comment]
This repo doesn't work, things moved to https://github.com/cybertronai/imagenet18

**Comment by yaroslavvb** [comment]
Oh I see, you are following "running locally" instructions. Looks like diux closed access to the files. Currently right now the only way is to train using AWS recipe since they are baked into AMI. I could reupload the files from the AMI image if it's helpful

**Comment by ymjiang** [comment]
@yaroslavvb Thank you for the reply. Yes, I am trying to reproduce the imagenet18 experiment locally, and I need the dataset.  

I already have the `ILSVRC2012_img_train` and `ILSVRC2012_img_val` dataset on local machines. (BTW, are they the same with what you show as "imagenet" in the dir tree?) 
I think what I actually need is imagenet-sz. Not sure what does 160 and 320 mean.

- ~/data
  - imagenet
    - train
    - validation
  - imagenet-sz
    - 160
      - train
      - validation
    - 320
      - train
      - validation

Since we don't have an access to AWS, it would be great if you could kindly reupload the files.

**Comment by ymjiang** [comment]
I am closing this issue. Thanks.
